//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StajProje2Entities : DbContext
    {
        public StajProje2Entities()
            : base("name=StajProje2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Proc_Kategoriler_Islem_Result> Proc_Kategoriler_Islem(string islem, Nullable<int> kategoriID, string kategoriBaslik)
        {
            var islemParameter = islem != null ?
                new ObjectParameter("Islem", islem) :
                new ObjectParameter("Islem", typeof(string));
    
            var kategoriIDParameter = kategoriID.HasValue ?
                new ObjectParameter("KategoriID", kategoriID) :
                new ObjectParameter("KategoriID", typeof(int));
    
            var kategoriBaslikParameter = kategoriBaslik != null ?
                new ObjectParameter("KategoriBaslik", kategoriBaslik) :
                new ObjectParameter("KategoriBaslik", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Kategoriler_Islem_Result>("Proc_Kategoriler_Islem", islemParameter, kategoriIDParameter, kategoriBaslikParameter);
        }
    
        public virtual ObjectResult<Proc_Urunler_Islem_Result> Proc_Urunler_Islem(string islem, Nullable<int> urunID, Nullable<int> kategoriID, string urunKodu, string urunBaslik, string urunAciklama, string urunResimUrl, Nullable<int> urunEskiFiyat, Nullable<int> urunInderm, Nullable<double> urunfiyat)
        {
            var islemParameter = islem != null ?
                new ObjectParameter("Islem", islem) :
                new ObjectParameter("Islem", typeof(string));
    
            var urunIDParameter = urunID.HasValue ?
                new ObjectParameter("UrunID", urunID) :
                new ObjectParameter("UrunID", typeof(int));
    
            var kategoriIDParameter = kategoriID.HasValue ?
                new ObjectParameter("KategoriID", kategoriID) :
                new ObjectParameter("KategoriID", typeof(int));
    
            var urunKoduParameter = urunKodu != null ?
                new ObjectParameter("UrunKodu", urunKodu) :
                new ObjectParameter("UrunKodu", typeof(string));
    
            var urunBaslikParameter = urunBaslik != null ?
                new ObjectParameter("UrunBaslik", urunBaslik) :
                new ObjectParameter("UrunBaslik", typeof(string));
    
            var urunAciklamaParameter = urunAciklama != null ?
                new ObjectParameter("UrunAciklama", urunAciklama) :
                new ObjectParameter("UrunAciklama", typeof(string));
    
            var urunResimUrlParameter = urunResimUrl != null ?
                new ObjectParameter("UrunResimUrl", urunResimUrl) :
                new ObjectParameter("UrunResimUrl", typeof(string));
    
            var urunEskiFiyatParameter = urunEskiFiyat.HasValue ?
                new ObjectParameter("UrunEskiFiyat", urunEskiFiyat) :
                new ObjectParameter("UrunEskiFiyat", typeof(int));
    
            var urunIndermParameter = urunInderm.HasValue ?
                new ObjectParameter("UrunInderm", urunInderm) :
                new ObjectParameter("UrunInderm", typeof(int));
    
            var urunfiyatParameter = urunfiyat.HasValue ?
                new ObjectParameter("Urunfiyat", urunfiyat) :
                new ObjectParameter("Urunfiyat", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Urunler_Islem_Result>("Proc_Urunler_Islem", islemParameter, urunIDParameter, kategoriIDParameter, urunKoduParameter, urunBaslikParameter, urunAciklamaParameter, urunResimUrlParameter, urunEskiFiyatParameter, urunIndermParameter, urunfiyatParameter);
        }
    }
}
